# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{jettr}
  s.version = "0.2.1"
  s.platform = %q{java}

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Ryan Heimbuch"]
  s.date = %q{2010-02-09}
  s.default_executable = %q{jettr}
  s.email = %q{rheimbuch@gmail.com}
  s.executables = ["jettr"]
  s.files = [
    ".gitignore",
     "Rakefile",
     "VERSION",
     "bin/jettr",
     "features/jettr/create_simple_server.feature",
     "features/jettr/step_definitions/create_server_steps.rb",
     "features/jettr/support/hooks.rb",
     "features/jettr/support/lib.rb",
     "lib/jettr.rb",
     "lib/jettr/command.rb",
     "lib/jettr/config.rb",
     "lib/jettr/handler.rb",
     "lib/jettr/handler/base.rb",
     "lib/jettr/handler/rails.rb",
     "lib/jettr/handler/simple_handler.rb",
     "lib/jettr/handler/web_app.rb",
     "lib/jettr/jars.rb",
     "lib/jettr/jars/akuma-1.3-jar-with-dependencies.jar",
     "lib/jettr/jars/core-3.1.1.jar",
     "lib/jettr/jars/jettr-java.jar",
     "lib/jettr/jars/jetty-6.1.14.jar",
     "lib/jettr/jars/jetty-plus-6.1.14.jar",
     "lib/jettr/jars/jetty-util-6.1.14.jar",
     "lib/jettr/jars/jruby-rack-0.9.6.jar",
     "lib/jettr/jars/jsp-2.1.jar",
     "lib/jettr/jars/jsp-api-2.1.jar",
     "lib/jettr/jars/servlet-api-2.5-6.1.14.jar",
     "lib/jettr/logger.rb",
     "lib/jettr/server.rb",
     "spec/.gitignore",
     "tasks/jettr.thor",
     "tasks/jeweler.rake"
  ]
  s.homepage = %q{http://github.com/rheimbuch/persvr}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Use Jetty from JRuby.}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<configatron>, [">= 1.5.1"])
      s.add_runtime_dependency(%q<log4r>, [">= 1.1.4"])
      s.add_runtime_dependency(%q<thor>, [">= 0"])
      s.add_runtime_dependency(%q<activesupport>, ["~> 2.3.5"])
    else
      s.add_dependency(%q<configatron>, [">= 1.5.1"])
      s.add_dependency(%q<log4r>, [">= 1.1.4"])
      s.add_dependency(%q<thor>, [">= 0"])
      s.add_dependency(%q<activesupport>, ["~> 2.3.5"])
    end
  else
    s.add_dependency(%q<configatron>, [">= 1.5.1"])
    s.add_dependency(%q<log4r>, [">= 1.1.4"])
    s.add_dependency(%q<thor>, [">= 0"])
    s.add_dependency(%q<activesupport>, ["~> 2.3.5"])
  end
end

